package proto

var Proto = `// auto-generated by terser-cli {{.GenerateTime}}
// {{.StructName}}Service proto {{.Comment}}
syntax = "proto3";
package proto;
import "query_list.proto";

// {{.StructName}}Service  {{.Comment}}
service {{.StructName}}Service {
      /**  name: 新增接口
      remark: 新增接口
      method: POST
      url: Create{{.StructName}} */
    rpc Create{{.StructName}} ({{.StructName}}Data) returns ({{.StructName}}IDData);
    /**  name: 修改接口
      remark: 修改接口
      method: POST
      url: Update{{.StructName}}List} */
    rpc Update{{.StructName}} ({{.StructName}}Data) returns ({{.StructName}}IDData);
    /**  name: 查询接口
      remark: 查询接口
      method: GET
      url: Describe{{.StructName}} */
    rpc Describe{{.StructName}} ({{.StructName}}IDData) returns ({{.StructName}}Data);
    /**  name: 删除接口
      remark: 删除接口
      method: POST
      url: Find{{.StructName}}List} */ 
    rpc Delete{{.StructName}} ({{.StructName}}IDData) returns ({{.StructName}}IDData);
    /**  name: 查询列表接口
      remark: 查询列表接口
      method: GET
      url: Find{{.StructName}}List} */ 
    rpc Find{{.StructName}}List (QueryParams) returns ({{.StructName}}List);
}

/** name: {{.StructName}}IDData
    remark: {{.StructName}}Id查询 */
message {{.StructName}}IDData { 
{{range .PrimaryKeys}}   /** remark: {{.Comment}} */
   {{.GoDataType}} {{.PropertyName}} = {{call Sum .Index 1}};
{{end}}}

/** name: {{.StructName}}Data
    remark: {{.StructName}}Model {{.Comment}} */
message {{.StructName}}Data { 
{{range .ColumnList}}    /** remark: {{.Comment}} */
    {{.GoDataType}} {{.PropertyName}}  = {{call Sum .Index 1}};
{{end}}}

/** name: {{.StructName}}List
    remark: {{.StructName}}查询列表 {{.Comment}} */
message {{.StructName}}List {
    /** remark: 分页信息 */
    PageInfo PageInfo = 1;
    /** remark: {{.StructName}}Data列表 */
    repeated {{.StructName}}Data DataList = 2;
}

// model.{{.StructName}} 转 proto.{{.StructName}}Data
//func ToPB{{.StructName}}Data(dbModel *model.{{.StructName}}) (pbModel *pb.{{.StructName}}Data) {
//	pbModel = &pb.{{.StructName}}Data{}{{range .ColumnList}}
//	pbModel.{{.PropertyName}} = dbModel.{{.PropertyName}}	// {{.Comment}} {{end}}
//	
//	return pbModel
//}
// proto.{{.StructName}}Data 转 model.{{.StructName}}
//func ToDB{{.StructName}}Data(pbModel *pb.{{.StructName}}Data) (dbModel *model.{{.StructName}}) {
//	dbModel = &model.{{.StructName}}{}{{range .ColumnList}}
//	dbModel.{{.PropertyName}} = pbModel.{{.PropertyName}}	// {{.Comment}} {{end}}
//
//	return dbModel
//}

`
