package proto

var Proto = `// auto-generated by terser-cli {{.GenerateTime}}
// {{.StructName}}Service proto {{.Comment}}
syntax = "proto3";
package proto;
import "query_list.proto";

// {{.StructName}}Service  {{.Comment}}
service {{.StructName}}Service {
    // 新增接口
    rpc Create{{.StructName}} ({{.StructName}}Data) returns ({{.StructName}}IDData);
    // 修改接口
    rpc Modify{{.StructName}} ({{.StructName}}Data) returns ({{.StructName}}IDData);
    // 查询接口
    rpc Describe{{.StructName}} ({{.StructName}}IDData) returns ({{.StructName}}Data);
    // 删除接口
    rpc Delete{{.StructName}} ({{.StructName}}IDData) returns ({{.StructName}}IDData);
    // 查询列表接口
    rpc Find{{.StructName}}List (QueryParams) returns ({{.StructName}}List);
}

// {{.StructName}} PK Query
message {{.StructName}}IDData { 
{{range .PrimaryKeys}}   {{.GoDataType}} {{.PropertyName}} = {{call Sum .Index 1}};	// {{.Comment}}
{{end}}}

// {{.StructName}}Model {{.Comment}}
message {{.StructName}}Data { 
{{range .ColumnList}}    {{.GoDataType}} {{.PropertyName}}  = {{call Sum .Index 1}};	// {{.Comment}}
{{end}}}

// {{.StructName}}查询列表: {{.Comment}} 
message {{.StructName}}List {
    PageInfo PageInfo = 1;				// 分页信息
    repeated {{.StructName}}Data DataList = 2;	// {{.StructName}}Data列表
}

// model.{{.StructName}} 转 proto.{{.StructName}}Data
//func ToPB{{.StructName}}Data(dbModel *model.{{.StructName}}) (pbModel *pb.{{.StructName}}Data) {
//	pbModel = &pb.{{.StructName}}Data{}{{range .ColumnList}}
//	pbModel.{{.PropertyName}} = dbModel.{{.PropertyName}}	// {{.Comment}} {{end}}
//	
//	return pbModel
//}
// proto.{{.StructName}}Data 转 model.{{.StructName}}
//func ToDB{{.StructName}}Data(pbModel *pb.{{.StructName}}Data) (dbModel *model.{{.StructName}}) {
//	dbModel = &model.{{.StructName}}{}{{range .ColumnList}}
//	dbModel.{{.PropertyName}} = pbModel.{{.PropertyName}}	// {{.Comment}} {{end}}
//
//	return dbModel
//}

`
